/** @type {import('stylelint').Config} */
export default {
  ignoreFiles: ['**/node_modules/**', '**/dist/**'],
  extends: ['stylelint-config-standard-scss', 'stylelint-prettier/recommended'],
  plugins: ['stylelint-order'],
  rules: {
    'font-family-no-duplicate-names': [true, { severity: 'error' }],
    'font-family-no-missing-generic-family-keyword': [
      true,
      {
        severity: 'error',
      },
    ],
    'font-family-name-quotes': [
      'always-unless-keyword',
      {
        severity: 'warning',
      },
    ],
    'length-zero-no-unit': [
      true,
      {
        ignore: ['custom-properties'],
        severity: 'warning',
      },
    ],
    'no-irregular-whitespace': [true, { severity: 'error' }],
    'property-no-unknown': [true, { severity: 'error' }],
    'block-no-empty': [true, { severity: 'warning' }],
    'selector-attribute-quotes': ['always', { severity: 'warning' }],
    'selector-pseudo-element-colon-notation': [
      'single',
      {
        severity: 'warning',
      },
    ],
    'selector-type-case': ['lower', { severity: 'warning' }],
    'value-keyword-case': ['lower', { severity: 'warning' }],
    'color-hex-length': ['short', { severity: 'warning' }],
    'comment-whitespace-inside': ['always', { severity: 'warning' }],
    'color-no-invalid-hex': [true, { severity: 'error' }],
    'function-calc-no-unspaced-operator': [true, { severity: 'warning' }],
    'function-name-case': ['lower', { severity: 'warning' }],
    'function-linear-gradient-no-nonstandard-direction': [
      true,
      {
        severity: 'error',
      },
    ],
    'string-no-newline': [true, { severity: 'error' }],
    'unit-no-unknown': [true, { severity: 'error' }],
    'keyframe-declaration-no-important': [true, { severity: 'error' }],
    'declaration-block-no-duplicate-properties': [
      true,
      {
        ignore: ['consecutive-duplicates'],
        severity: 'error',
      },
    ],
    'declaration-block-no-shorthand-property-overrides': [
      true,
      {
        severity: 'error',
      },
    ],
    'selector-pseudo-class-no-unknown': [true, { severity: 'error' }],
    'selector-pseudo-element-no-unknown': [true, { severity: 'error' }],
    'selector-type-no-unknown': [true, { severity: 'error' }],
    'no-duplicate-selectors': [true, { severity: 'error' }],
    'keyframe-block-no-duplicate-selectors': [true, { severity: 'error' }],
    'custom-property-empty-line-before': [
      'always',
      {
        except: ['after-custom-property', 'first-nested'],
        ignore: ['after-comment'],
        severity: 'warning',
      },
    ],
    'declaration-empty-line-before': [
      'always',
      {
        except: ['first-nested', 'after-declaration'],
        ignore: ['after-comment'],
        severity: 'warning',
      },
    ],
    'order/order': [
      ['dollar-variables', 'custom-properties', 'declarations'],
      { severity: 'warning' },
    ],
    'order/properties-order': [
      [
        'all',
        'content',
        'position',
        'inset',
        'top',
        'right',
        'bottom',
        'left',
        'z-index',
        'display',
        'vertical-align',
        'flex',
        'flex-grow',
        'flex-shrink',
        'flex-basis',
        'flex-direction',
        'flex-flow',
        'flex-wrap',
        'grid',
        'grid-area',
        'grid-template',
        'grid-template-areas',
        'grid-template-rows',
        'grid-template-columns',
        'grid-row',
        'grid-row-start',
        'grid-row-end',
        'grid-column',
        'grid-column-start',
        'grid-column-end',
        'grid-auto-rows',
        'grid-auto-columns',
        'grid-auto-flow',
        'grid-gap',
        'grid-row-gap',
        'grid-column-gap',
        'gap',
        'row-gap',
        'column-gap',
        'place-content',
        'align-content',
        'justify-content',
        'place-items',
        'align-items',
        'justify-items',
        'place-self',
        'align-self',
        'justify-self',
        'order',
        'float',
        'clear',
        'object-fit',
        'object-position',
        'overflow',
        'overflow-x',
        'overflow-y',
        'overflow-scrolling',
        'clip',

        //
        'box-sizing',
        'width',
        'min-width',
        'max-width',
        'height',
        'min-height',
        'max-height',
        'aspect-ratio',
        'margin',
        'margin-inline',
        'margin-block',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'padding',
        'padding-inline',
        'padding-block',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        'border',
        'border-spacing',
        'border-collapse',
        'border-width',
        'border-style',
        'border-color',
        'border-top',
        'border-top-width',
        'border-top-style',
        'border-top-color',
        'border-right',
        'border-right-width',
        'border-right-style',
        'border-right-color',
        'border-bottom',
        'border-bottom-width',
        'border-bottom-style',
        'border-bottom-color',
        'border-left',
        'border-left-width',
        'border-left-style',
        'border-left-color',
        'border-radius',
        'border-top-left-radius',
        'border-top-right-radius',
        'border-bottom-right-radius',
        'border-bottom-left-radius',
        'border-image',
        'border-image-source',
        'border-image-slice',
        'border-image-width',
        'border-image-outset',
        'border-image-repeat',
        'border-top-image',
        'border-right-image',
        'border-bottom-image',
        'border-left-image',
        'border-corner-image',
        'border-top-left-image',
        'border-top-right-image',
        'border-bottom-right-image',
        'border-bottom-left-image',

        //
        'font',
        'font-weight',
        'font-style',
        'font-variant',
        'font-size-adjust',
        'font-stretch',
        'font-size',
        'font-family',
        'src',
        'line-height',
        'letter-spacing',
        'quotes',
        'counter-increment',
        'counter-reset',
        '-ms-writing-mode',
        'text-align',
        'text-align-last',
        'text-decoration',
        'text-emphasis',
        'text-emphasis-position',
        'text-emphasis-style',
        'text-emphasis-color',
        'text-indent',
        'text-justify',
        'text-outline',
        'text-transform',
        'text-wrap',
        'text-overflow',
        'text-overflow-ellipsis',
        'text-overflow-mode',
        'text-shadow',
        'white-space',
        'word-spacing',
        'word-wrap',
        'word-break',
        'overflow-wrap',
        'tab-size',
        'hyphens',
        'interpolation-mode',

        //
        'background',
        'background-color',
        'background-image',
        'background-attachment',
        'background-position',
        'background-position-x',
        'background-position-y',
        'background-clip',
        'background-origin',
        'background-size',
        'background-repeat',
        'color',
        'box-decoration-break',
        'box-shadow',
        'outline',
        'outline-width',
        'outline-style',
        'outline-color',
        'outline-offset',
        'table-layout',
        'caption-side',
        'empty-cells',
        'list-style',
        'list-style-position',
        'list-style-type',
        'list-style-image',

        //
        'opacity',
        'visibility',
        'filter',
        'resize',
        'cursor',
        'pointer-events',
        'user-select',

        //
        'unicode-bidi',
        'direction',
        'columns',
        'column-span',
        'column-width',
        'column-count',
        'column-fill',
        'column-rule',
        'column-rule-width',
        'column-rule-style',
        'column-rule-color',
        'break-before',
        'break-inside',
        'break-after',
        'page-break-before',
        'page-break-inside',
        'page-break-after',
        'orphans',
        'widows',
        'zoom',
        'max-zoom',
        'min-zoom',
        'user-zoom',
        'orientation',
        'fill',
        'stroke',

        //
        'transition',
        'transition-delay',
        'transition-timing-function',
        'transition-duration',
        'transition-property',
        'transform',
        'transform-origin',
        'animation',
        'animation-name',
        'animation-duration',
        'animation-play-state',
        'animation-timing-function',
        'animation-delay',
        'animation-iteration-count',
        'animation-direction',
        'animation-fill-mode',
      ],
      {
        unspecified: 'bottom',
        severity: 'warning',
      },
    ],
    'comment-no-empty': [true, { severity: 'warning' }],
    'media-feature-name-no-unknown': [true, { severity: 'error' }],
    'at-rule-no-unknown': null,
    'scss/at-rule-no-unknown': true,
    'no-descending-specificity': [true, { severity: 'error' }],
    'no-duplicate-at-import-rules': [true, { severity: 'error' }],
    'no-empty-source': [true, { severity: 'warning' }],
    'declaration-block-no-duplicate-custom-properties': [
      true,
      {
        severity: 'error',
      },
    ],
    'named-grid-areas-no-invalid': [true, { severity: 'error' }],
    'no-invalid-position-at-import-rule': [true, { severity: 'error' }],
    'custom-property-no-missing-var-function': [true, { severity: 'error' }],
    'annotation-no-unknown': [true, { severity: 'error' }],
    'function-url-no-scheme-relative': [true, { severity: 'warning' }],
    'shorthand-property-no-redundant-values': [true, { severity: 'warning' }],
    'value-no-vendor-prefix': [true, { severity: 'warning' }],
    'property-no-vendor-prefix': [true, { severity: 'warning' }],
    'declaration-no-important': [true, { severity: 'error' }],
    'selector-no-vendor-prefix': [true, { severity: 'warning' }],
    'at-rule-no-vendor-prefix': [true, { severity: 'warning' }],
    'no-unknown-animations': [true, { severity: 'error' }],
    'time-min-milliseconds': [100, { severity: 'warning' }],
    'declaration-block-no-redundant-longhand-properties': null,
    'media-feature-name-no-vendor-prefix': [true, { severity: 'warning' }],
    'color-function-notation': ['modern', { severity: 'warning' }],
    'scss/selector-no-redundant-nesting-selector': true,
    'selector-class-pattern':
      '^[a-z]([-]?[a-z0-9]+)*(__[a-z0-9]([-]?[a-z0-9]+)*)?(--[a-z0-9]([-]?[a-z0-9]+)*)?$',
  },
};
